### ISSUE TITLE
[bug] Servers that have no icons assigned show up as CVR icon instead of the usual text

### ISSUE THREAD

**Issue by Bluscream** [Inazumanotenshi/ChilloutVR-Theme#2]
How it currently looks like
![Vesktop_IbD8aC9xLj](https://github.com/Inazumanotenshi/ChilloutVR-Theme/assets/3318223/01910ca8-1764-45e8-89e3-825b5f3fbc80)

How it's supposed to look like (the V)
![Vesktop_md69kpXDCl](https://github.com/Inazumanotenshi/ChilloutVR-Theme/assets/3318223/aa224458-3946-482d-8b93-e232d8282a73)

i think it's because the `.childWrapper_f90abb` is also on those servers so they get the `content: var(--ChilloutSymbol);` treatment. a possible solution would be somehow ignoring the ones that are inside `div[data-dnd-name]` potentially not sure

**Comment by Inazumanotenshi** [comment]
Fixed in version 0.5.4
