### ISSUE TITLE
profile view broke

### ISSUE THREAD

**Issue by Bluscream** [Inazumanotenshi/ChilloutVR-Theme#3]
Seems like in the last update the quick profile preview in the lower left corner broke when in a voice call atleast

![image](https://github.com/user-attachments/assets/9fbf4676-27aa-4d1d-b1d7-782de9cc3eee)

**Comment by Inazumanotenshi** [comment]
Already fixed in version 0.5.10. Please check first updates before creating an issue.

**Comment by Bluscream** [comment]
I wrote the issue 10 minutes before you pushed your fix :) Thanks anyway!

**Comment by Inazumanotenshi** [comment]
You wrote it a day after the fix. Please check then next time if you send
![image](https://github.com/user-attachments/assets/b7d84e15-5df1-483f-bcf7-0a78d5d30565)
![image](https://github.com/user-attachments/assets/340a63d2-1018-4ba1-9043-bc806af9003b)

**Comment by Bluscream** [comment]
I am using the minified theme for performance and you only pushed that **after** my issue :)

**Comment by Inazumanotenshi** [comment]
Then write this the next time and dont expect to know...
